easy_admin:
    site_name: 'Hoomie'
    design:
        menu:
            - { label: 'Dashboard', route: 'app_dashboard', icon: 'dashboard'}
            - { entity: 'User', icon: 'user' }
    user:
        display_name: true
        avatar_property_path: 'gravatar'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        User:
            class: App\Entity\User
