controllers:
    resource: ../../src/Controller/
    type: annotation

profile_controller:
    resource: ../../src/Controller/PageController.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
